### ISSUE TITLE
Перестал работать на PHP 8.2

### ISSUE THREAD

**Issue by 1nSaneRu** [VKCOM/vk-php-sdk#102]
PHP Fatal error:  Uncaught Error: Undefined constant "**VK\TransportClient\Curl\CURLOPT_HEADER**" in /vendor/vkcom/vk-php-sdk/src/VK/TransportClient/Curl/CurlHttpClient.php:25
Stack trace:
#0 /vendor/vkcom/vk-php-sdk/src/VK/Client/VKApiRequest.php(50): VK\TransportClient\Curl\CurlHttpClient->__construct()
#1 /vendor/vkcom/vk-php-sdk/src/VK/Client/VKApiClient.php(232): VK\Client\VKApiRequest->__construct()
#2 /vk.php(13): VK\Client\VKApiClient->__construct()
#3 {main}
  thrown in **/vendor/vkcom/vk-php-sdk/src/VK/TransportClient/Curl/CurlHttpClient.php on line 25**

**Comment by 1nSaneRu** [comment]
мой косяк, почему-то PHP не обновил автоматически как минимум curl модуль, кто знает какие еще...
