### ISSUE TITLE
Class 'VK\Exceptions\Api\VKApiException' not found

### ISSUE THREAD

**Issue by TrueGameover** [VKCOM/vk-php-sdk#21]
```
yii\base\ErrorException: Class 'VK\Exceptions\Api\VKApiException' not found in E:\PHP\pikabustore\engine\vendor\vkcom\vk-php-sdk\src\VK\Exceptions\Api\VKApiParamUserIdException.php:5
Stack trace:
#0 E:\PHP\pikabustore\engine\vendor\composer\ClassLoader.php(322): ::Composer\Autoload\includeFile(''E:\\\\PHP\\\\pikab...')
#1 E:\PHP\pikabustore\engine\vendor\vkcom\vk-php-sdk\src\VK\Exceptions\Api\ExceptionMapper.php(67): Composer\Autoload\ClassLoader->loadClass(''VK\\\\Exceptions...')
#2 E:\PHP\pikabustore\engine\vendor\vkcom\vk-php-sdk\src\VK\Exceptions\Api\ExceptionMapper.php(67): ::spl_autoload_call(''VK\\\\Exceptions...')
#3 E:\PHP\pikabustore\engine\vendor\vkcom\vk-php-sdk\src\VK\Client\VKApiRequest.php(134): VK\Exceptions\Api\ExceptionMapper::parse('class VK\\Client...')
#4 E:\PHP\pikabustore\engine\vendor\vkcom\vk-php-sdk\src\VK\Client\VKApiRequest.php(90): VK\Client\VKApiRequest->parseResponse('class VK\\Transp...')
#5 E:\PHP\pikabustore\engine\vendor\vkcom\vk-php-sdk\src\VK\Actions\Users.php(53): VK\Client\VKApiRequest->post(''users.get'', ''ed2d3e12ed2d3e...', 'array ('user_id...')
#6 E:\PHP\pikabustore\engine\controllers\ListingController.php(123): VK\Actions\Users->get(''ed2d3e12ed2d3e...', 'array ('user_id...')
#7 E:\PHP\pikabustore\engine\vendor\yiisoft\yii2\base\InlineAction.php(57): app\controllers\ListingController->actionIndex(''a-tvoj-truba-s...')
#8 E:\PHP\pikabustore\engine\vendor\yiisoft\yii2\base\InlineAction.php(57): ::call_user_func_array:{E:\PHP\pikabustore\engine\vendor\yiisoft\yii2\base\InlineAction.php:57}('array (0 => cla...', 'array (0 => 'a-...')
#9 E:\PHP\pikabustore\engine\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams('array ('slug' =...')
#10 E:\PHP\pikabustore\engine\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction(''index'', 'array ('slug' =...')
#11 E:\PHP\pikabustore\engine\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction(''listing/index'', 'array ('slug' =...')
#12 E:\PHP\pikabustore\engine\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest('class yii\\web\\R...')
#13 E:\PHP\pikabustore\index.php(9): yii\base\Application->run()
#14 {main}

```
Установлено через composer. 
В исключении подгружает по такому пути
`'E:\\PHP\\pikabustore\\engine\\vendor\\composer/../vkcom/vk-php-sdk/src/VK\\Exceptions\\Api\\VKApiParamUserIdException.php'`

Я так понимаю автозагрузка не происходит из-за отсутствия класса по указанному в namespace пути

```
namespace VK\Exceptions\Api;

class VKApiException extends \Exception
```
Если скопировать класс по указанному пути неймспейса проблема ликвидируется.

"vkcom/vk-php-sdk": "^0.1.7",

**Comment by wumvi** [comment]
Pull ревест подавали
https://github.com/VKCOM/vk-php-sdk/pull/11

**Comment by TrueGameover** [comment]
О, отлично
