### ISSUE TITLE
VKClientException: Invalid http status: 0 при работе через HTTP/2

### ISSUE THREAD

**Issue by Nik-mmzd** [VKCOM/vk-php-sdk#36]
https://github.com/VKCOM/vk-php-sdk/blob/master/src/VK/TransportClient/Curl/CurlHttpClient.php#L187
Не может распарсить HTTP status code при запросе через HTTP/2 (`HTTP/2 401` не попадает под регулярку)

**Comment by zakharov-dm** [comment]
Да, та же проблема.

**Comment by mrzlab630** [comment]
мое решение:

 protected function getHttpStatus(string $raw_response_header): int {
        preg_match('@HTTP/(\d|\d\.\d)\s+(\d+)\s+.*@', $raw_response_header, $match);
        return (int)$match[2];
    }

1. изменил регулярку с |HTTP/\d\.\d\s+(\d+)\s+.*| на @HTTP/(\d|\d\.\d)\s+(\d+)\s+.*@
2. $match[2]

**Comment by sizeg** [comment]
@Nik-mmzd проблема актуальна. Проект заброшен?

Релиз 5.101.0
PHP 7.4

```
PHP Fatal error: Uncaught VKExceptionsVKClientException: Invalid http status: 0
in /var/www/esh-derevenskoe.ru/vendor/vkcom/vk-php-sdk/src/VK/Client/VKApiRequest.php:184

Stack trace:

 #0 /var/www/esh-derevenskoe.ru/vendor/vkcom/vk-php-sdk/src/VK/Client/VKApiRequest.php(124): VKClientVKApiRequest->checkHttpStatus()
 #1 /var/www/esh-derevenskoe.ru/vendor/vkcom/vk-php-sdk/src/VK/Client/VKApiRequest.php(88): VKClientVKApiRequest->parseResponse()
 #2 /var/www/esh-derevenskoe.ru/vendor/vkcom/vk-php-sdk/src/VK/Actions/Photos.php(265): VKClientVKApiRequest->post()
 #3 /var/www/esh-derevenskoe.ru/admin/model/tool/vk_product_update.php(102): VKActionsPhotos->getMarketUploadServer()
 #4 /var/www/esh-derevenskoe.ru/admin/model/tool/vk_product_update.php(507): ModelToolVkProductUpdate->vkProductUpdate()
 #5 /var/www/esh-derevenskoe.ru/system/engine/loader.php(297): ModelToolVkProductUpdate->checkVkUpdateData()
 #6 /var/www/esh-derevenskoe.ru/system/engine/proxy.php(25): Loader->{closure}()
 #7 /var/www/esh-derevenskoe.ru/admin/controlle in /var/www/esh-derevenskoe.ru/vendor/vkcom/vk-php-sdk/src/VK/Client/VKApiRequest.php on line 184
```

**Comment by sizeg** [comment]
@Nik-mmzd проблема актуальна. Проект заброшен?

Релиз 5.101.0
PHP 7.4

```
PHP Fatal error: Uncaught VKExceptionsVKClientException: Invalid http status: 0
in /var/www/vendor/vkcom/vk-php-sdk/src/VK/Client/VKApiRequest.php:184
Stack trace:

 #0 /var/www/vendor/vkcom/vk-php-sdk/src/VK/Client/VKApiRequest.php(124): VKClientVKApiRequest->checkHttpStatus()
 #1 /var/www/vendor/vkcom/vk-php-sdk/src/VK/Client/VKApiRequest.php(88): VKClientVKApiRequest->parseResponse()
 #2 /var/www/vendor/vkcom/vk-php-sdk/src/VK/Actions/Photos.php(265): VKClientVKApiRequest->post()
 #3 /var/www/admin/model/tool/vk_product_update.php(102): VKActionsPhotos->getMarketUploadServer()
 #4 /var/www/admin/model/tool/vk_product_update.php(507): ModelToolVkProductUpdate->vkProductUpdate()
 #5 /var/www/system/engine/loader.php(297): ModelToolVkProductUpdate->checkVkUpdateData()
 #6 /var/www/system/engine/proxy.php(25): Loader->{closure}()
 #7 /var/www/admin/controlle in /var/www/vendor/vkcom/vk-php-sdk/src/VK/Client/VKApiRequest.php on line 184
```

**Comment by sizeg** [comment]
Я подебажил немного. Статус 200 через curl можно получить достаточно просто без всяких регулярок.

```
    public function sendRequest(string $url, array $opts) {
        $curl = curl_init($url);

        curl_setopt_array($curl, $this->initial_opts + $opts);

        $response = curl_exec($curl);

        $curl_error_code = curl_errno($curl);
        $curl_error = curl_error($curl);

        //  The last response code
        $http_code = curl_getinfo($curl, CURLINFO_RESPONSE_CODE);

        curl_close($curl);

        if ($curl_error || $curl_error_code) {
            $error_msg = "Failed curl request. Curl error {$curl_error_code}";
            if ($curl_error) {
                $error_msg .= ": {$curl_error}";
            }

            $error_msg .= '.';

            throw new TransportRequestException($error_msg);
        }

        return $this->parseRawResponse($response);
    }
```

**Comment by sizeg** [comment]
https://github.com/VKCOM/vk-php-sdk/pull/82
